### ISSUE TITLE
Add handling of default exports

### ISSUE THREAD

**Issue by gforge** [estruyf/vscode-typescript-exportallmodules#1]
It would be nice if files with `/^export default/` exported that member as `export { default as ${fileWithoutExtension} } from './${fileWithoutExtension}'`.

**Comment by estruyf** [comment]
Should this be an option? Or should it be always like this?

Will your files that contain a `default` contain other exports?

**Comment by gforge** [comment]
As it is a common export style that has been around for a long time I suggest that it should be on by default. I have started to drop the `default` export as it adds little value and named exports have mostly benefits as I see it.

 I think that one can expect that in TypeScript settings there will most likely be a mix of types being exported together with some core function, e.g. NavBar & NavBarProps.

**Comment by estruyf** [comment]
Now that we have support for named exports in the extension, I've also included support for handling `default` exports.

Defaults will be exported with the function's name, class name, interface's name, or the filename will be used if not provided.
