### ISSUE TITLE
about wildcards

### ISSUE THREAD

**Issue by cctv1237** [estruyf/vscode-typescript-exportallmodules#10]
Hi bro, just wanna ask if the folderListener support path wildcards? 
Looks like it's not supoort "src/**/" if I want to watch directories nested to all levels under src/

**Comment by estruyf** [comment]
Sorry @cctv1237 for the late answer, but wildcards are currently not supported.

**Comment by literallyMello** [comment]
I also wish this was a feature I have a top level nested folder and just want to add a listener for that vs having to add one for each and every folder.

**Comment by lsw1164** [comment]
I also with it, plz
