### ISSUE TITLE
Add an option to add a ".js" suffix to exports

### ISSUE THREAD

**Issue by chepseskhaf** [estruyf/vscode-typescript-exportallmodules#11]
Hi,

When targeting native ES6 modules, a TS import from a file needs to end with ".js", even if the file does not exists yet.
VS Code seems to be aware of this and can automatically use this pattern when suggesting imports.

For example, this tool tries to solve the issue: https://github.com/Zoltu/typescript-transformer-append-js-extension
TypeScript issue: https://github.com/microsoft/TypeScript/issues/16577

It would be nice to have an option to append the ".js" in the generated index.ts files.

Thanks for your work.

**Comment by estruyf** [comment]
Thanks @rgicquel for the suggestion.

**Comment by estruyf** [comment]
Based on the suggestion from @sharky98, I have added a new setting, `exportall.config.exportFileExtension`, in which you can manually define the file extension. By default, it is set to `null`. If you want to export with `.js` as the filename, you can just set the setting to `js`.

**Comment by estruyf** [comment]
It has been released in version `v2.11.0`.
