### ISSUE TITLE
Don't write to file if contents would be the same

### ISSUE THREAD

**Issue by mirague** [estruyf/vscode-typescript-exportallmodules#12]
It seems the index files are touched each time a change is made in the watched subdirectories, even if the contents are the same. This causes file watchers to trigger and restart/hot-reload the process. I've got a temporary workaround by having it ignore all `index.ts` files, which works, but now I need to restart my process every time I add, move or rename a file.

Would it be possible to not write to the index.ts file if its contents are unchanged?

**Comment by estruyf** [comment]
Thanks @mirague, this probably requires an extra check to validate the file content against the newly generated content but should be doable.

**Comment by estruyf** [comment]
The change is included in version `2.4.0`. Thanks again for the suggestion!
