### ISSUE TITLE
Automatically do `export type` instead of `export` for types and interfaces

### ISSUE THREAD

**Issue by rszemplinski** [estruyf/vscode-typescript-exportallmodules#13]
Was wondering if this feature already exists or is something being thought about?

**Comment by estruyf** [comment]
Thanks @rszemplinski for the suggestion. It doesn't exist right now but is definitely a good enhancement for the extension.

**Comment by estruyf** [comment]
This feature has been implemented and is available in version 2.8.0 thanks to @mrheault
