### ISSUE TITLE
Bug with folder names like 1.0.0 (e.g. used for API versioning)

### ISSUE THREAD

**Issue by iDschepe** [estruyf/vscode-typescript-exportallmodules#15]
If you have a folder named like this: 

_1.0.0_

index.ts will result in something like: 

`export * from "./1.0";`

which is resulting in the following error: 

`Cannot find module './1.0' or its corresponding type declarations.ts(2307)`

**Comment by estruyf** [comment]
Thanks @iDschepe for opening the issue. Will take a look at it to fix it.

**Comment by iDschepe** [comment]
Seems to work for me! Thanks for your response!
