### ISSUE TITLE
feat: Add setting for adding banner to generated barrels

### ISSUE THREAD

**Issue by rubiin** [estruyf/vscode-typescript-exportallmodules#16]
This setting should allow the generated barrel file to have a nice banner.
For example `index.ts`
```ts

// THIS FILE WAS AUTOMATICALLY GENERATED (DO NOT MODIFY)

export * from './application.entity';
export * from './banks.entity';

```

**Comment by rubiin** [comment]
@estruyf any updates

**Comment by estruyf** [comment]
No update yet. Like the idea, can be added in the next version.

**Comment by rubiin** [comment]
Yeah. I was using a cli app and it supports it

**Comment by estruyf** [comment]
A new setting is now available to specify the autogenerated message you want to add at the top of your barrel files. The setting to use is: `exportall.config.message`.

Version 2.5.0 of the extension has been released.
