### ISSUE TITLE
Unable to resolve filesystem provider with relative file path 'c/... on "Export all modules" 

### ISSUE THREAD

**Issue by PavelOparin** [estruyf/vscode-typescript-exportallmodules#31]
After update from 2.7.0 to 2.9.0 "Export all modules" command from VSCode file explorer is not working anymore. In output it sends message error : "Unable to resolve filesystem provider with relative file path 'c/...' ". If I change extension version back to 2.7.0 it solves problem. Tested it on Windows 10 and 11 and tried to downgrade VSCode but only extension downgrade solved issue.

**Comment by estruyf** [comment]
Thanks to @mrheault this has been fixed in version `2.9.1`.
